### ISSUE TITLE
Configuration get deleted at every update (Download Directory)

### ISSUE THREAD

**Issue by tr1p0p** [YunoHost-Apps/simple-torrent_ynh#66]
So, running yunohost simple-torrent on rpi 4. 

I just wanna notice to you 2 things :

-Why they're just no way to configure the download directory on the web ui on this ? Seem to be the bare minimum for a torrent app on a self-hosted server...

-And why, after we found we have to edit a file with nano on terminal for that, the update progress clean and deleted EVERYTIME this files ?

This two things making simple-torrent like... not easy at all. Can someone make this more simple, like the name ?

**Comment by ericgaspar** [comment]
> -Why they're just no way to configure the download directory on the web ui on this ? Seem to be the bare minimum for a torrent app on a self-hosted server...
> 

This is out of the scope of this script. You should address the question upstream: https://github.com/boypt/simple-torrent.

> -And why, after we found we have to edit a file with nano on terminal for that, the update progress clean and deleted EVERYTIME this files ?
> 

This is because Simple-Torrent changed the format of the configuration file from JSON to YAML. We want to make sure every user gets the updated YAML config file before keeping it when upgrading
